### PR TITLE
call registerDeclartion so it wont error

### LINKED ISSUE #5: Messy console warnings related to default export identifier injection
Getting many of these console errors when running the tests using this library so that output is getting unreadable:

```
The exported identifier "_DefaultExportValue" is not declared in Babel's scope tracker
 as a JavaScript value binding, and "@babel/plugin-transform-typescript"
 never encountered it as a TypeScript type declaration.
 It will be treated as a JavaScript value.This problem is likely caused by another plugin injecting
 "_DefaultExportValue" without registering it in the scope tracker. If you are the author
 of that plugin, please use "scope.registerDeclaration(declarationPath)". 
```

### PR DESCRIPTION
**Pull request by ricksmit3000**
fixes #5

### CODE REVIEW

**Comment by jacobroufa** [comment]
This gives me a build error with: `TypeError: path.isLabeledStatement is not a function`

**Comment by TranquilMarmot** [comment]
I get the same build error trying to use this. I think a much more involved solution needs to be done to properly handle registering the scopes.

**Comment by priyank-p** [comment]
Can you folks provide the code being used (reducing it down to just the bit that causes the error if possible) to debug this? I guess I might be able to quickly fix this given I learned babel plugin APIs for #8.

**Comment by TranquilMarmot** [comment]
Our setup is complex enough that there's no way I could provide it here; I think a basic repro could be set up by using this webpack plugin along with the `@babel/preset-typescript` preset

**Comment by priyank-p** [comment]
@TranquilMarmot I just came across [this issue](https://github.com/babel/babel/issues/10264). Can you check weather just updating babel and @babel/preset-typescript fixes this issue if they are not using the latest verison?

**Comment by quiqueg** [comment]
@priyank-p The error is still present on the latest release of babel and `@babel/preset-typescript`. [Here's a link to a min-reproducible case](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAYiEMC8MDeMBGBDATgLhgHIcAvImAXwG4AoWgUwA8AHEXWAEwYDNsBXADawEIAHQ5c1IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Ctypescript%2Cenv&prettier=false&targets=&version=7.10.4&externalPlugins=babel-plugin-rewire-ts%401.3.3) (open your browser's DevTools console to see the error message.

**Comment by priyank-p** [comment]
@quiqueg Thanks for the minimal repro case; it is really nice to just get to debugging.

**Comment by priyank-p** [comment]
(Quick update: Fixed the bug for the code present above; I still to do the same for other cases.)

**Comment by quiqueg** [comment]
@priyank-p  I've been looking into this as well. I assume you've fixed the `_DefaultExportValue` errors by doing:
```diff
- path.replaceWith(
+ const [declarationPath] = path.replaceWith(
    t.classDeclaration(
      exportIdentifier,
      existingClassDeclaration.superClass,
      existingClassDeclaration.body,
      existingClassDeclaration.decorators || []
    )
- );
+ ) || [];
+ if (declarationPath) {
+   scope.registerDeclaration(declarationPath);
+ }
```
in the 3 places where `DefaultExportValue` declaration is added ([1](https://github.com/rosswarren/babel-plugin-rewire-ts/blob/master/src/babel-plugin-rewire.js#L118), [2](https://github.com/rosswarren/babel-plugin-rewire-ts/blob/master/src/babel-plugin-rewire.js#L134), and [3](https://github.com/rosswarren/babel-plugin-rewire-ts/blob/master/src/babel-plugin-rewire.js#L157)), but the `_get__`, `_set__`, `_reset__`, and `_RewireAPI__` errors are still TODO?

I've been wondering if it's possible to fix those errors _without_ refactoring all of [Templates.js](https://github.com/rosswarren/babel-plugin-rewire-ts/blob/master/src/Templates.js) into a set of proper AST operations (`t.createIdentifier(...)`, `t.exportNamedDeclaration(...)`, etc.), but I'm starting to think that will be the only option. What do you think?

**Comment by priyank-p** [comment]
@quiqueg I fixed one of three the places you linked above, I didn't have time to fix more.

Do `__get__` and friends cause the same error? I'd think they won't because we pass `Identifier` or proper AST Node via babel `Template` so that cares of doing this for us, whereas we didn't pass this `DefaultExportVariable` through the Template, hence this issue.

If they do, in which case I'd be surprised, we can add a helper method that does this for all AST nodes we create in `prepend{something}`, (I don't know the name from the top of my head) so we don't need to do a lot of refactoring.

**Comment by priyank-p** [comment]
Also, if you already fixed other things, can you make a PR, Thanks?

**Comment by TranquilMarmot** [comment]
Here are all the unique error messages we get from `babel-plugin-rewire`:

```
The exported identifier "_get__" is not declared in Babel's scope tracker
as a JavaScript value binding, and "@babel/plugin-transform-typescript"
never encountered it as a TypeScript type declaration.
It will be treated as a JavaScript value.

This problem is likely caused by another plugin injecting
"_get__" without registering it in the scope tracker. If you are the author
 of that plugin, please use "scope.registerDeclaration(declarationPath)".
```

```
The exported identifier "_set__" is not declared in Babel's scope tracker
as a JavaScript value binding, and "@babel/plugin-transform-typescript"
never encountered it as a TypeScript type declaration.
It will be treated as a JavaScript value.

This problem is likely caused by another plugin injecting
"_set__" without registering it in the scope tracker. If you are the author
 of that plugin, please use "scope.registerDeclaration(declarationPath)".
```

```
The exported identifier "_reset__" is not declared in Babel's scope tracker
as a JavaScript value binding, and "@babel/plugin-transform-typescript"
never encountered it as a TypeScript type declaration.
It will be treated as a JavaScript value.

This problem is likely caused by another plugin injecting
"_reset__" without registering it in the scope tracker. If you are the author
 of that plugin, please use "scope.registerDeclaration(declarationPath)".
```

```
The exported identifier "_RewireAPI__" is not declared in Babel's scope tracker
as a JavaScript value binding, and "@babel/plugin-transform-typescript"
never encountered it as a TypeScript type declaration.
It will be treated as a JavaScript value.

This problem is likely caused by another plugin injecting
"_RewireAPI__" without registering it in the scope tracker. If you are the author
 of that plugin, please use "scope.registerDeclaration(declarationPath)".
```

We get about ~500Kb of log lines like this for each test run :cry:

**Comment by priyank-p** [comment]
Oh, so we need to do this for all the variables we inject based on the logs. @TranquilMarmot those warning are harmless so you should be fine though of course we should fix this issue quickly.

**Comment by priyank-p** [comment]
Closing since #10 fixes this issue.

**Pull request closed without merging**
